# Generated by Django 5.2.8 on 2025-11-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_age_user_size_user_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='weight_goal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
