# Generated by Django 5.2.8 on 2025-12-03 20:05

import django.db.models.deletion
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_age_alter_user_size_alter_user_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='commitment_months',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SubscriptionEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('commitment_months', models.PositiveIntegerField(default=0)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='core.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_engagements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-start_date',),
            },
        ),
    ]
