# Generated by Django 5.2.8 on 2025-12-03 20:20

from django.db import migrations


def seed_subscriptions(apps, schema_editor):
    Subscription = apps.get_model("core", "Subscription")
    presets = [
        {
            "code": "STARTER",
            "name": "Starter",
            "price_monthly": 9.90,
            "level_rank": 1,
            "commitment_months": 0,
        },
        {
            "code": "PRO",
            "name": "Pro",
            "price_monthly": 19.90,
            "level_rank": 2,
            "commitment_months": 6,
        },
        {
            "code": "ELITE",
            "name": "Elite",
            "price_monthly": 29.90,
            "level_rank": 3,
            "commitment_months": 12,
        },
    ]

    for preset in presets:
        Subscription.objects.update_or_create(
            code=preset["code"],
            defaults=preset,
        )


def unseed_subscriptions(apps, schema_editor):
    Subscription = apps.get_model("core", "Subscription")
    Subscription.objects.filter(code__in=["STARTER", "PRO", "ELITE"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_subscription_commitment_subscriptionengagement'),
    ]

    operations = [
        migrations.RunPython(seed_subscriptions, unseed_subscriptions),
    ]
