# Generated by Django 5.2.8 on 2025-12-03 20:40

from django.db import migrations


def enforce_commitments(apps, schema_editor):
    Subscription = apps.get_model("core", "Subscription")
    updates = [
        ("PRO", {"commitment_months": 6}),
        ("ELITE", {"commitment_months": 12}),
    ]
    for code, defaults in updates:
        Subscription.objects.update_or_create(code=code, defaults=defaults)


def rollback_commitments(apps, schema_editor):
    Subscription = apps.get_model("core", "Subscription")
    Subscription.objects.filter(code__in=["PRO", "ELITE"]).update(commitment_months=0)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_seed_subscriptions'),
    ]

    operations = [
        migrations.RunPython(enforce_commitments, rollback_commitments),
    ]
