# Generated by Django 6.0 on 2025-12-12 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_enforce_commitment_on_pro_elite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(blank=True, default='Non défini', max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='goal_type',
            field=models.CharField(blank=True, default='Non défini', max_length=50),
        ),
        migrations.AlterField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_workouts', to=settings.AUTH_USER_MODEL),
        ),
    ]
