# Generated by ChatGPT to seed a default admin profile
from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_admin_user(apps, schema_editor):
    User = apps.get_model("core", "User")
    username = "admin"
    email = "admin@example.com"
    defaults = {
        "email": email,
        "password": make_password("admin123"),
        "is_staff": True,
        "is_superuser": True,
        "role": "admin",
    }
    User.objects.update_or_create(username=username, defaults=defaults)


def delete_admin_user(apps, schema_editor):
    User = apps.get_model("core", "User")
    User.objects.filter(username="admin", is_superuser=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_adminuser_coach_user_role"),
    ]

    operations = [
        migrations.RunPython(create_admin_user, delete_admin_user),
    ]
