# Generated by Django 5.2.9 on 2025-12-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_seed_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_type',
            field=models.CharField(default='Général', max_length=50),
        ),
    ]
