# Generated by Django 5.2.9 on 2025-12-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_badge_image_alter_badge_code_alter_badge_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
