# Generated by Django 6.0 on 2025-12-12 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts', to='programs.program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='goal_type',
            field=models.CharField(choices=[('Prise de masse', 'Prise de masse'), ('Perte de poids', 'Perte de poids'), ('Cardio', 'Cardio'), ('Force', 'Force'), ('Hypertrophie', 'Hypertrophie')], default='Non défini', max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='level',
            field=models.CharField(choices=[('Débutant', 'Débutant'), ('Intermédiaire', 'Intermédiaire'), ('Avancé', 'Avancé')], default='Débutant', max_length=20),
        ),
        migrations.AlterField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL),
        ),
    ]
