# Generated by Django 6.0 on 2025-12-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_workout_program_alter_program_goal_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
