# Generated by Django 6.0 on 2025-12-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_workout_duration_minutes_workout_workout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
