# Generated by Django 6.0 on 2025-12-13 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_workout_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='duration',
        ),
        migrations.AlterField(
            model_name='program',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='programexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='program_exercises_links', to='programs.exercise'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs_workouts', to='programs.program'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs_workouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='programs_exercise_sets', to='programs.exercise'),
        ),
    ]
